version: "3.9"

services:
  goiex-postgres-server:
    image: goiex-postgres-centos
    networks:
      dev:
        aliases:
          - db
    ports:
      - "5423:5432"
    environment:
        - DB_USER
        - DB_PASSWORD
        - DB_NAME
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
  goiex-app:
    image: goiex-app
    networks:
      dev:
        aliases:
          - app
    environment:
        - DB_USER
        - DB_PASSWORD
        - DB_NAME
        - PG_CONNECT=postgres://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
        - IEX_TOKEN=${IEX_SANDBOX_TOKEN}
    volumes:
      - ./app/src:/app

volumes:
  postgres-data:

networks:
  dev:
