version: "3.9"

services:
  goiex-db:
    image: goiex-postgres12-centos
    networks:
      dev:
        aliases:
          - db
    ports:
      - "5432:5432"
    environment:
        - DB_USER
        - DB_PASSWORD
        - DB_NAME
        - PG_CONNECT=postgres://${DB_USER}:${DB_PASSWORD}@localhost/${DB_NAME}
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      
  goiex-cache:
    image: redis
    networks:
      dev:
        aliases:
          - redis
    ports:
      - "6379:6379"

  goiex-front:
    image: goiex-ngnix-dev
    networks:
      dev:
        aliases:
          - front
    ports:
      - "80:80"
    volumes:
      - ./front/goiex_front:/app/goiex_front

  goiex-app:
    image: goiex-app-dev
    networks:
      dev:
        aliases:
          - app
    ports:
      - "8080:8080"
    environment:
        - DB_USER
        - DB_PASSWORD
        - DB_NAME
        - PG_CONNECT=postgres://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
        - IEX_TOKEN=${IEX_SANDBOX_TOKEN}
    volumes:
      - ./app:/app
    depends_on:
      - goiex-db
      - goiex-cache

volumes:
  postgres-data:

networks:
  dev:
