version: "3.9"

services:
  goiex-postgres-server:
    image: goiex-postgres12-centos
    networks:
      dev:
        aliases:
          - db
    ports:
      - "5432:5432"
    environment:
        - DB_USER
        - DB_PASSWORD
        - DB_NAME
        - PG_CONNECT=postgres://${DB_USER}:${DB_PASSWORD}@localhost/${DB_NAME}
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

  goiex-app:
    image: goiex-app-dev
    #command: tail -f /dev/null
    networks:
      dev:
        aliases:
          - app
    ports:
      - "8080:8080"
    environment:
        - DB_USER
        - DB_PASSWORD
        - DB_NAME
        - PG_CONNECT=postgres://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
        - IEX_TOKEN=${IEX_SANDBOX_TOKEN}
    volumes:
      - ./app:/app
    depends_on:
      - goiex-postgres-server

volumes:
  postgres-data:

networks:
  dev:
