FROM goiex-ngnix

ADD goiex_front /app/goiex_front
WORKDIR /app/goiex_front
RUN apk add --update npm
RUN node --version
RUN npm --version
RUN npm install -g nodemon
RUN npm install
RUN npm run build
ENV PORT=80
ENV PATH="${PATH}:/app/goiex_front/node_modules/.bin"
CMD ["nodemon", "-x", "npm", "start"]